
default: &defaults
  adapter: postgresql
  encoding: utf8
  pool: 5
  host: localhost
  username: postgres
  password: 12345678

development:
  <<: *defaults
  adapter: postgresql
  database: template
